all: command-0 command-1 command-2 command-3 command-4 command-5 command-6 command-7 command-8 command-9

command-0: 
	sleep 0.0 && echo "" > command-0

command-1: 
	sleep 0.0 && echo "" > command-1

command-2: 
	sleep 0.0 && echo "" > command-2

command-3: 
	sleep 0.0 && echo "" > command-3

command-4: 
	sleep 0.0 && echo "" > command-4

command-5: 
	sleep 0.0 && echo "" > command-5

command-6: 
	sleep 0.0 && echo "" > command-6

command-7: 
	sleep 0.0 && echo "" > command-7

command-8: 
	sleep 0.0 && echo "" > command-8

command-9: 
	sleep 0.0 && echo "" > command-9

clean: 
	rm command-0 && rm command-1 && rm command-2 && rm command-3 && rm command-4 && rm command-5 && rm command-6 && rm command-7 && rm command-8 && rm command-9
