# Ceci est un makefile test afin de concevoir efficacement le parsing

var1 = lmao

coucou1.txt:
	echo coucou >> coucou1.txt

coucou2.txt:
	echo coucou >> coucou2.txt

list: coucou1.txt coucou2.txt
	ls *.txt > tmp.txt