               lol
# Ceci est un makefile test afin de concevoir efficacement le parsing

&foo= "lol"                                      """"       lalala

    lol: lmao
	echo $(&foo)
	s
foo2 = "lmao"

lmao   :
	echo $(foo2)